---
title: "Network Analysis"
author: "Ernst Forrer, Enea Gentilini, Carolin Bronowicz"
date: '`r Sys.Date()`'
output: 
  html_document:
  code_folding: show
  fig_caption: yes
  highlight: tango
  number_sections: no
  theme: default
  toc: yes
  toc_depth: 2
  toc_float: yes
---
  
<style>
  body {text-align: justify}
</style>
  
  
# Introduction
  
  This tutorial shows how to model networks


```{r, echo=FALSE}
# Preliminaries
rm(list=ls())             # clean the environment
options(scipen=6)         # display digits properly!! not the scientific version
options(digits.secs=6)    # use milliseconds in Date/Time data types
options(warning=FALSE)    # don't show warnings
```

Damit wir starten können, laden wir uns die Liste der Betriebspunkte und die Tabelle der geplanten und tatsächlichen Ankunfts/Abfahrtzeiten herunter. Diese werden von der SBB frei zur verfügung gestellt.

```{r}
betriebspunkte <- read.csv("https://data.sbb.ch/explore/dataset/linie-mit-betriebspunkten/download/?format=csv&timezone=Europe/Berlin&lang=de&use_labels_for_header=true&csv_separator=%3B", sep=";")
head(betriebspunkte)

IstSoll_Zeiten <- read.csv("https://data.sbb.ch/explore/dataset/ist-daten-sbb/download/?format=csv&timezone=Europe/Berlin&lang=de&use_labels_for_header=true&csv_separator=%3B", sep=";")
head(IstSoll_Zeiten)
```
